/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-03-17 07:14:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.nicePage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Projects/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1606299370802L));
    _jspx_dependants.put("jar:file:/C:/Projects/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html style=\"font-size: 16px;\">\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"keywords\"\n");
      out.write("\tcontent=\"Learn Everyday, Join online courses today, Train Your Brain Today!, Learn to enjoyevery minute of your life., Online Learning, Innovations in Online Learning, Education and Learning, 01, 02, 03, 04, Contact Us\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"page_type\" content=\"np-template-header-footer-from-plugin\">\n");
      out.write("<title>Home</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/nicepage.css\" media=\"screen\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/Home.css\" media=\"screen\">\n");
      out.write("<script class=\"u-script\" type=\"text/javascript\" src=\"js/jquery.js\" defer=\"\"></script>\n");
      out.write("<script class=\"u-script\" type=\"text/javascript\" src=\"js/nicepage.js\"\n");
      out.write("\tdefer=\"\"></script>\n");
      out.write("<meta name=\"generator\" content=\"Nicepage 3.9.0, nicepage.com\">\n");
      out.write("<link id=\"u-theme-google-font\" rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i\">\n");
      out.write("<link id=\"u-page-google-font\" rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|PT+Sans:400,400i,700,700i|Oswald:200,300,400,500,600,700|Archivo+Black:400\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"application/ld+json\">{\n");
      out.write("\t\t\"@context\": \"http://schema.org\",\n");
      out.write("\t\t\"@type\": \"Organization\",\n");
      out.write("\t\t\"name\": \"\",\n");
      out.write("\t\t\"url\": \"index.html\"\n");
      out.write("}</script>\n");
      out.write("<meta property=\"og:title\" content=\"Home\">\n");
      out.write("<meta property=\"og:type\" content=\"website\">\n");
      out.write("<meta name=\"theme-color\" content=\"#478ac9\">\n");
      out.write("<link rel=\"canonical\" href=\"index.html\">\n");
      out.write("<meta property=\"og:url\" content=\"index.html\">\n");
      out.write("</head>\n");
      out.write("<body class=\"u-body\">\n");
      out.write("\n");
      out.write("<!-- header start -->\n");
      out.write("\t<header class=\"u-clearfix u-header u-header\" id=\"sec-85c8\">\n");
      out.write("\t\t<div class=\"u-clearfix u-sheet u-sheet-1\">\n");
      out.write("\t\t\t<nav\n");
      out.write("\t\t\t\tclass=\"u-align-left u-menu u-menu-dropdown u-offcanvas u-offcanvas-shift u-menu-1\"\n");
      out.write("\t\t\t\tdata-responsive-from=\"MD\">\n");
      out.write("\t\t\t\t<div class=\"menu-collapse\"\n");
      out.write("\t\t\t\t\tstyle=\"font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;\">\n");
      out.write("\t\t\t\t\t<a\n");
      out.write("\t\t\t\t\t\tclass=\"u-button-style u-custom-active-border-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\"\n");
      out.write("\t\t\t\t\t\thref=\"#\"> <svg>\n");
      out.write("\t\t\t\t\t\t\t<use xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n");
      out.write("\t\t\t\t\t\t\t\txlink:href=\"#menu-hamburger\"></use></svg> <svg version=\"1.1\"\n");
      out.write("\t\t\t\t\t\t\txmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("\t\t\t\t\t\t\txmlns:xlink=\"http://www.w3.org/1999/xlink\">\n");
      out.write("\t\t\t\t\t\t\t<defs>\n");
      out.write("\t\t\t\t\t\t\t<symbol id=\"menu-hamburger\" viewBox=\"0 0 16 16\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 16px; height: 16px;\">\n");
      out.write("\t\t\t\t\t\t\t<rect y=\"1\" width=\"16\" height=\"2\"></rect>\n");
      out.write("\t\t\t\t\t\t\t<rect y=\"7\" width=\"16\" height=\"2\"></rect>\n");
      out.write("\t\t\t\t\t\t\t<rect y=\"13\" width=\"16\" height=\"2\"></rect>\n");
      out.write("</symbol>\n");
      out.write("</defs></svg>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"u-custom-menu u-nav-container\">\n");
      out.write("\t\t\t\t\t<ul class=\"u-nav u-spacing-30 u-unstyled u-nav-1\">\n");
      out.write("\t\t\t\t\t\t<li class=\"u-nav-item\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-grey-90 u-text-hover-grey-90\"\n");
      out.write("\t\t\t\t\t\t\thref=\"Home.html#introduce\" data-page-id=\"292223659\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"u-nav-item\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-grey-90 u-text-hover-grey-90\"\n");
      out.write("\t\t\t\t\t\t\thref=\"Home.html#framework\" data-page-id=\"292223659\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Stats</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"u-nav-item\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-grey-90 u-text-hover-grey-90\"\n");
      out.write("\t\t\t\t\t\t\thref=\"resume.html#sec-8581\" data-page-id=\"45112699\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Resume</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"u-nav-item\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-grey-90 u-text-hover-grey-90\"\n");
      out.write("\t\t\t\t\t\t\thref=\"Home.html#contact\" data-page-id=\"292223659\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Contact me</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"u-nav-item\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-base u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-grey-90 u-text-hover-grey-90\"\n");
      out.write("\t\t\t\t\t\t\thref=\"forum.html#sec-8581\" data-page-id=\"60385609\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Forum</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"u-custom-menu u-nav-container-collapse\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav\">\n");
      out.write("\t\t\t\t\t\t<div class=\"u-sidenav-overflow\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-menu-close\"></div>\n");
      out.write("\t\t\t\t\t\t\t<ul\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"Home.html#introduce\" data-page-id=\"292223659\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"Home.html#framework\" data-page-id=\"292223659\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Stats</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"resume.html#sec-8581\" data-page-id=\"45112699\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Resume</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"Home.html#contact\" data-page-id=\"292223659\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Contact me</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"forum.html#sec-8581\" data-page-id=\"60385609\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"padding: 10px 0px;\">Forum</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"u-black u-menu-overlay u-opacity u-opacity-70\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<h4 class=\"u-text u-text-1\">예비 개발자 조찬익입니다.</h4>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- header end -->\n");
      out.write("\t<section\n");
      out.write("\t\tclass=\"u-clearfix u-image u-valign-middle-md u-valign-middle-sm u-valign-middle-xs u-section-1\"\n");
      out.write("\t\tid=\"introduce\">\n");
      out.write("\t\t<div class=\"u-clearfix u-layout-wrap u-layout-wrap-1\">\n");
      out.write("\t\t\t<div class=\"u-gutter-0 u-layout\">\n");
      out.write("\t\t\t\t<div class=\"u-layout-row\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-align-left u-container-style u-layout-cell u-size-29 u-layout-cell-1\">\n");
      out.write("\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-1\">\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"u-text u-text-1\">Who I am</h6>\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"u-text u-text-2\">개발자 조찬익 입니다.</h1>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"u-text u-text-3\">\n");
      out.write("\t\t\t\t\t\t\t\t저는 컴퓨터를 좋아합니다. <br> 컴퓨터를 정복하고 싶습니다.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.nicepage.com/website-mockup\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"u-active-palette-1-dark-2 u-btn u-btn-rectangle u-button-style u-custom-font u-font-pt-sans u-hover-palette-1-dark-2 u-palette-1-dark-3 u-radius-0 u-btn-1\">read\n");
      out.write("\t\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-align-right u-container-style u-image u-layout-cell u-size-31 u-image-1\"\n");
      out.write("\t\t\t\t\t\tdata-image-width=\"698\" data-image-height=\"928\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-container-layout u-valign-bottom u-container-layout-2\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<section class=\"u-align-center u-clearfix u-section-2\" id=\"framework\">\n");
      out.write("\t\t<div class=\"u-clearfix u-sheet u-sheet-1\">\n");
      out.write("\t\t\t<div class=\"u-shape u-shape-svg u-text-palette-4-base u-shape-1\">\n");
      out.write("\t\t\t\t<svg class=\"u-svg-link\" preserveAspectRatio=\"none\"\n");
      out.write("\t\t\t\t\tviewBox=\"0 0 160 80\" style=\"\">\n");
      out.write("\t\t\t\t\t<use xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n");
      out.write("\t\t\t\t\t\txlink:href=\"#svg-0b7f\"></use></svg>\n");
      out.write("\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("\t\t\t\t\txmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\"\n");
      out.write("\t\t\t\t\txml:space=\"preserve\" class=\"u-svg-content\" viewBox=\"0 0 160 80\"\n");
      out.write("\t\t\t\t\tx=\"0px\" y=\"0px\" id=\"svg-0b7f\"\n");
      out.write("\t\t\t\t\tstyle=\"enable-background: new 0 0 160 80;\">\n");
      out.write("\t\t\t\t\t<path d=\"M160,0H0c0,44.2,35.8,80,80,80S160,44.2,160,0z\"></path></svg>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<h1 class=\"u-custom-font u-text u-text-body-alt-color u-text-1\">사용하는 프레임워크</h1>\n");
      out.write("\t\t\t<p class=\"u-align-center u-text u-text-body-alt-color u-text-2\">The\n");
      out.write("\t\t\t\tframework I can use.</p>\n");
      out.write("\t\t\t<div\n");
      out.write("\t\t\t\tclass=\"u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-list u-repeater u-list-1\">\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"u-container-style u-grey-5 u-list-item u-repeater-item u-list-item-1\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-container-layout u-similar-container u-valign-top u-container-layout-1\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-align-left u-container-style u-group u-image u-radius-50 u-shape-round u-image-1\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-2\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"u-align-center u-text u-text-3\">HTML5</h5>\n");
      out.write("\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-4\">WHATWG와 W3C가 발표하는 HTML의 최신 버전으로, 2014년 10월 28일 완전히 표준화되었다. \n");
      out.write("\t\t\t\t\t\tXHTML에서 다시 HTML로 회귀하게 되었다. 따라서 HTML5는 XHTML의 상위 버전이 아니라, HTML4.01의 상위 버전이다. </p>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-active-none u-border-2 u-border-palette-4-base u-btn u-btn-rectangle u-button-style u-hover-none u-none u-text-body-color u-btn-1\">learn\n");
      out.write("\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"u-container-style u-grey-5 u-list-item u-repeater-item u-list-item-2\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-container-layout u-similar-container u-valign-top u-container-layout-3\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-align-left u-container-style u-group u-image u-radius-50 u-shape-round u-image-2\"\n");
      out.write("\t\t\t\t\t\t\tdata-image-width=\"512\" data-image-height=\"512\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-4\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"u-align-center u-text u-text-5\">CSS</h5>\n");
      out.write("\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-6\">HTML 등의 마크업 언어로 작성된 문서가 실제로 웹사이트에 표현되는 방법을 정해주는 언어.  \n");
      out.write("\t\t\t\t\t\tCSS의 C가 Cascading의 약자인데, 이는 상위 요소의 스타일 속성을 자손 요소들에게 상속시켜주는 모습이 DOM 트리구조에서 마치 폭포수처럼 내려가는 모습을 닮았기 때문이다</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-active-none u-border-2 u-border-palette-4-base u-btn u-btn-rectangle u-button-style u-hover-none u-none u-text-body-color u-btn-2\">learn\n");
      out.write("\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"u-container-style u-grey-5 u-list-item u-repeater-item u-list-item-3\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-container-layout u-similar-container u-valign-top u-container-layout-5\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-align-left u-container-style u-group u-image u-radius-50 u-shape-round u-image-3\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-6\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"u-align-center u-text u-text-7\">JAVASCRIPT</h5>\n");
      out.write("\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-8\">모질라 재단의 프로토타입기반의 프로그래밍 언어로, 스크립트 언어에 해당된다. 특수한 목적이 아닌 이상 모든 웹 브라우저에 인터프리터가 내장되어 있다. </p>\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.nicepage.com/landing-page\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-active-none u-border-2 u-border-palette-4-base u-btn u-btn-rectangle u-button-style u-hover-none u-none u-text-body-color u-btn-3\">learn\n");
      out.write("\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"u-container-style u-grey-5 u-list-item u-repeater-item u-list-item-4\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-container-layout u-similar-container u-valign-top u-container-layout-7\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-align-left u-container-style u-group u-image u-radius-50 u-shape-round u-image-4\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-8\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"u-align-center u-text u-text-9\">SPRING</h5>\n");
      out.write("\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-10\">Java/Kotlin 기반의 웹 프레임워크. \n");
      out.write("\t\t\t\t\t\t로드 존슨(Rod Johnson)이 2002년에 출판한 저서 Expert One-on-One J2EE Design and Development에서 선보인 소스 코드를 시작으로 점점 발전하게 되었다.  \n");
      out.write("\t\t\t\t\t\t스프링 프레임워크 프로젝트를 간편하게 설정할 수 있도록 도와주는 서브 프로젝트 스프링 부트가 있으며, 현재는 스프링 부트 위주로 기능이 추가되고 있다.</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.nicepage.com/static-site-generator\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-active-none u-border-2 u-border-palette-4-base u-btn u-btn-rectangle u-button-style u-hover-none u-none u-text-body-color u-btn-4\">learn\n");
      out.write("\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"u-container-style u-grey-5 u-list-item u-repeater-item u-list-item-5\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-container-layout u-similar-container u-valign-top u-container-layout-9\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-align-left u-container-style u-group u-image u-radius-50 u-shape-round u-image-5\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-10\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"u-align-center u-text u-text-11\">JAVA</h5>\n");
      out.write("\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-12\">썬 마이크로시스템즈에서 1995년에 개발한 객체 지향 프로그래밍 언어. 창시자는 제임스 고슬링이다. \n");
      out.write("\t\t\t\t\t\t2010년에 오라클이 썬 마이크로시스템즈을 인수하면서 Java의 저작권을 소유하였다. \n");
      out.write("\t\t\t\t\t\t현재는 OpenJDK는 GPL2이나 오라클이 배포하는 Oracle JDK는 상업라이선스로 오라클이 돈독 올랐는지 2019년 1월부터 유료화정책을 강화하고 있다. </p>\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.nicepage.com/static-site-generator\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-active-none u-border-2 u-border-palette-4-base u-btn u-btn-rectangle u-button-style u-hover-none u-none u-text-body-color u-btn-5\">learn\n");
      out.write("\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"u-container-style u-grey-5 u-list-item u-repeater-item u-list-item-6\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"u-container-layout u-similar-container u-valign-top u-container-layout-11\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-align-left u-container-style u-group u-image u-radius-50 u-shape-round u-image-6\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-12\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"u-align-center u-text u-text-13\">H2DATABASE</h5>\n");
      out.write("\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-14\">H2는 자바로 작성된 관계형 데이터베이스 관리 시스템이다. 자바 애플리케이션에 임베드하거나 클라이언트-서버 모드에서 구동할 수 있다.</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.nicepage.com/static-site-generator\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-active-none u-border-2 u-border-palette-4-base u-btn u-btn-rectangle u-button-style u-hover-none u-none u-text-body-color u-btn-6\">learn\n");
      out.write("\t\t\t\t\t\t\tmore</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("<!-- footer -->\n");
      out.write("\t<footer class=\"u-align-left u-clearfix u-footer u-grey-80 u-footer\"\n");
      out.write("\t\tid=\"sec-266b\">\n");
      out.write("\t\t<div class=\"u-clearfix u-sheet u-sheet-1\">\n");
      out.write("\t\t\t<div\n");
      out.write("\t\t\t\tclass=\"u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1\">\n");
      out.write("\t\t\t\t<div class=\"u-layout\">\n");
      out.write("\t\t\t\t\t<div class=\"u-layout-row\">\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-container-style u-layout-cell u-size-20 u-layout-cell-1\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-1\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"u-text u-text-1\">Address</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-2\">저는 전라남도 순천에 거주합니다.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-container-style u-layout-cell u-size-20 u-layout-cell-2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-2\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"u-align-left u-text u-text-3\">Phone &amp; E-mail</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"u-align-left u-text u-text-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t010-9876-5432<br>jochanig@xxxxxxxxx.com\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"u-container-style u-layout-cell u-size-20 u-layout-cell-3\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"u-container-layout u-container-layout-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"u-text u-text-5\">Blog</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"u-text u-text-6\">blog.naver.com/jochanig</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t <section class=\"u-backlink u-clearfix u-grey-80\">\n");
      out.write("\t\t<a class=\"u-link\" href=\"https://nicepage.com/html5-template\"\n");
      out.write("\t\t\ttarget=\"_blank\"> <span>HTML5 Template</span>\n");
      out.write("\t\t</a>\n");
      out.write("\t\t<p class=\"u-text\">\n");
      out.write("\t\t\t<span>created with</span>\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<a class=\"u-link\" href=\"https://nicepage.com/\" target=\"_blank\"> <span>Website\n");
      out.write("\t\t\t\tBuilder Software</span>\n");
      out.write("\t\t</a>.\n");
      out.write("\t</section> \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
